/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSignupRouteImport } from './routes/_layout/signup'
import { Route as LayoutLoginRouteImport } from './routes/_layout/login'
import { Route as LayoutProtectedRouteImport } from './routes/_layout/_protected'
import { Route as LayoutProductIdRouteImport } from './routes/_layout/product.$id'
import { Route as LayoutProtectedPurchasesRouteImport } from './routes/_layout/_protected/purchases'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSignupRoute = LayoutSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLoginRoute = LayoutLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedRoute = LayoutProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductIdRoute = LayoutProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProtectedPurchasesRoute =
  LayoutProtectedPurchasesRouteImport.update({
    id: '/purchases',
    path: '/purchases',
    getParentRoute: () => LayoutProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/purchases': typeof LayoutProtectedPurchasesRoute
  '/product/$id': typeof LayoutProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/login': typeof LayoutLoginRoute
  '/signup': typeof LayoutSignupRoute
  '/purchases': typeof LayoutProtectedPurchasesRoute
  '/product/$id': typeof LayoutProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_protected': typeof LayoutProtectedRouteWithChildren
  '/_layout/login': typeof LayoutLoginRoute
  '/_layout/signup': typeof LayoutSignupRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_protected/purchases': typeof LayoutProtectedPurchasesRoute
  '/_layout/product/$id': typeof LayoutProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/purchases' | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/purchases' | '/product/$id'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_protected'
    | '/_layout/login'
    | '/_layout/signup'
    | '/_layout/'
    | '/_layout/_protected/purchases'
    | '/_layout/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/signup': {
      id: '/_layout/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof LayoutSignupRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/login': {
      id: '/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutLoginRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected': {
      id: '/_layout/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutProtectedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/product/$id': {
      id: '/_layout/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof LayoutProductIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_protected/purchases': {
      id: '/_layout/_protected/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof LayoutProtectedPurchasesRouteImport
      parentRoute: typeof LayoutProtectedRoute
    }
  }
}

interface LayoutProtectedRouteChildren {
  LayoutProtectedPurchasesRoute: typeof LayoutProtectedPurchasesRoute
}

const LayoutProtectedRouteChildren: LayoutProtectedRouteChildren = {
  LayoutProtectedPurchasesRoute: LayoutProtectedPurchasesRoute,
}

const LayoutProtectedRouteWithChildren = LayoutProtectedRoute._addFileChildren(
  LayoutProtectedRouteChildren,
)

interface LayoutRouteChildren {
  LayoutProtectedRoute: typeof LayoutProtectedRouteWithChildren
  LayoutLoginRoute: typeof LayoutLoginRoute
  LayoutSignupRoute: typeof LayoutSignupRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutProductIdRoute: typeof LayoutProductIdRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProtectedRoute: LayoutProtectedRouteWithChildren,
  LayoutLoginRoute: LayoutLoginRoute,
  LayoutSignupRoute: LayoutSignupRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutProductIdRoute: LayoutProductIdRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
